### ISSUE TITLE
ENH: Add qip.noise section in tutorials page

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip.github.io#108]
We need to add a section in the tutorials page under the quantum circuits section. This could be a section per se, in order to make it stand out clearly. It should be referenced at the beginning of the page with a label too. @BoxiLi can you take care of it? Or else I can.

**Comment by BoxiLi** [comment]
Hi Nathan, I don't really know how to do that yet. Might need some study... If this is urgent, could you add this section?
What about
- quantum information processing
     - quantum circuit
     - processors (or devices)

**Comment by nathanshammah** [comment]
Solved by #109
