### ISSUE TITLE
Add news on the qutip projects and blog links

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip.github.io#117]
Add news on the qutip GSOC 2020 projects and link to Sidhant's, Asad's and Jake's blog.

**Comment by nathanshammah** [comment]
@araza6 can you take care of this?

**Comment by araza6** [comment]
Jake: https://www.binhbar.com/posts/2020/06/design-draft-data-structure-specifications/
Sidhant: https://sarsid.wordpress.com/2020/06/14/an-introduction-to-quantum-measurements-in-qutip/
Asad: https://araza6.github.io/posts/autodiff/autodiff/

**Comment by nathanshammah** [comment]
Hi @araza6, maybe this was not explicit enough: Can you open a PR on this repository and update the news section there, with the relevant information in style with http://qutip.org/news.html? The point of GSoC is to help students perform open source software development. This is not strictly part of your project but I thought it could help you to have at least a couple of PRs in the qutip organization repositories, cc @quantshah.

**Comment by araza6** [comment]
Alright, I'll take care of it
