### ISSUE TITLE
Fixing the "hidden underscore" problem

### ISSUE THREAD

**Issue by jakelishman** [qutip/qutip.github.io#120]
Hi guys,

I was just messing around with my own Sphinx stuff, and I've stumbled upon the way to get GitHub pages to recognise files and folders that begin with an underscore (like `_static` and so forth).  It's simple, but incredibly esoteric - you just drop a file called `.nojekyll` in the HTML root, and magically they'll all work again.

I don't know how your deploy process goes for building this repo from the `qutip/qutip-docs` one so I didn't make a PR, but hopefully this helps simplify things a bit.

@nathanshammah.

**Comment by nathanshammah** [comment]
That would be great. @tehruhn did it once off, but I think that the current "how-to" relies on the release distribution guide ([here](https://github.com/qutip/qutip-doc/blob/master/release_distribution.rst#copying-new-files)) and [this](https://github.com/qutip/qutip.github.io/blob/master/docs/remove_leading_underscores.py) code snippet by @ajgpitch. 

If this simplifies this bit, please go on. 

By the way, I recently interacted (in another repo) with Githubpages' nojekill configuration file. It turns out that one can simplify documentation release quite a bit by pointing to the `/docs/` folder (+ some tweaking). I wonder if we can ever use this to automate a bit the releases.

**Comment by jakelishman** [comment]
Yeah, this should remove the need for Alex's underscore removal script, since it fixes the underlying problem that GitHub ignores files that start with an underscore.

I've successfully hosted some Sphinx-built docs by doing this at https://jakelishman.github.io/qutip-devguide (base repo at https://github.com/jakelishman/qutip-devguide), though my weirdness there is that that git repo effectively has two completely separate repositories in it - the branches `master` and `gh-pages` share 0 commits, and even have a completely different directory structure within them.

I'll have a go at getting the full QuTiP documentation building on my machine and make a PR at some point (though probably not immediately).

**Comment by jakelishman** [comment]
Alex pointed out (via email) that the root of the website uses Liquid templates that need ot be processed with Jekyll, so it's not good enough to simply put in a `.nojekyll` file.

I see two possible other ways (as in, to avoid the underscore converter file) to solve this.

1. add `html_static_path = ["static"]` to `conf.py` in Sphinx (and similar for other underscored folders) so that the underscores are never generated in the first place
2. manually include the underscore folders in Jekyll's `_config.yml` file, but doing something like

```yaml
include:
  - docs/_static
  - docs/_sources
```

For point 2, my quick testing made it seem like Jekyll or GH pages is kind of finicky, and not always very quick to notice changes to included files.  I'm also not sure how well globbing works in Jekyll's configuration files, and we would effectively want to completely turn off Jekyll processing inside the Sphinx documentation folders.

For point 1, this should work, so long as we don't have _any_ files beginning with underscores generated by Sphinx.

**Comment by hodgestar** [comment]
I have an idea to address this by deploy the docs as a separate github-pages site so that they appear as `https://qutip.org/qutip-docs/` and don't have to be manually copied into this repository at all.

**Comment by hodgestar** [comment]
We can close this once #193 is merged.
