### ISSUE TITLE
QuTiP 4.4 documentation points to latest build

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip.github.io#121]
See http://qutip.org/documentation.html.

One needs to change the "Online HTML documentation" link for 4.4 and make sure that it points to 4.4 in https://github.com/qutip/qutip.github.io/tree/master/docs.

**Comment by nathanshammah** [comment]
Any help is appreciated, cc. @araza6 @jakelishman @sarsid.

**Comment by jakelishman** [comment]
Closed by #122.
