### ISSUE TITLE
Broken link on tutorials page

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip.github.io#166]
There is a broken link at qutip.org/tutorials
[Time-dependent Bloch-Redfield quantum dot](https://nbviewer.org/github/qutip/qutip-notebooks/blob/master/examples/brmesolve-time-dependent-Liouvillian.ipynb)
https://nbviewer.org/github/qutip/qutip-notebooks/blob/master/examples/brmesolve-time-dependent-Liouvillian.ipynb

Cc @nwlambert.

**Comment by hodgestar** [comment]
This link works for me. I thought it might have been fixed by #165, but that was merged on Oct 12. Not sure what happened, but closing for now.
