### ISSUE TITLE
Possible syntax error

### ISSUE THREAD

**Issue by kwyip** [qutip/qutip.github.io#34]
When running the example on [http://qutip.org/docs/3.1.0/guide/guide-bloch.html#bloch-config]

I encounter the `SyntaxError: invalid syntax`  on the line
`  ffmpeg -r 20 -b 1800 -i bloch_%01d.png bloch.mp4`.

While on Directly Generating an Animation section,
I encounter `NameError: name 'Bloch' is not defined` on the line
    `sphere = Bloch(axes=ax)`.

Maybe this is just due to my old version of qutip? Thanks.

**Comment by nonhermitian** [comment]
That command is run from the Linux command​ line and not Python.

**Comment by smcufpa** [comment]
Run:

[1] from qutip import *

[2] b = Bloch()

or 

 from qutip import *

 b = Bloch()
