### ISSUE TITLE
sigmap() wrongly tested as sigmam()

### ISSUE THREAD

**Issue by kwyip** [qutip/qutip.github.io#38]
http://qutip.org/docs/3.1.0/apidoc/functions.html

sigmap() wrongly tested as sigmam(), under `sigmap()`

**Comment by nathanshammah** [comment]
The docs API picked a typo in the docstrings of `sigmap()` in operators.py. PR [#957](https://github.com/qutip/qutip/pull/957) is now fixing it.  It will automatically appear in the online documentation from version 4.4.
