### ISSUE TITLE
Links to Jupyter notebooks dead

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip.github.io#43]
A few of the links to Jupyter notebooks in the online documentation are dead. However, they are referred to correctly in the tutorials section

**Comment by nathanshammah** [comment]
I went through the whole documentation (qutip.org/docs/latest) and I could not find any link to notebooks. I found only a general link to the [tutorials](http://qutip.org/docs/latest/guide/dynamics/dynamics-time.html#methods-for-writing-time-dependent-operators) section that works fine. Do you remember what were you referring to?

**Comment by quantshah** [comment]
I think I was referring to some links inside the online documentation back then. I cannot figure them out now so probably we can close this.
