### ISSUE TITLE
transform keeps tensor structure

### ISSUE THREAD

**Issue by chrisgee** [qutip/qutip.github.io#49]
I understand that basis transforms are in development. But I saw one thing that might be worth considering:

The dims propery of property is unaffected by doing a transform even though nothing guerantees that the product structure remains. Partial traces become meaningless (unless the origin of that structure is kept). 

Either one has to keep a copy of the transform in the transformed object to still be able to trace out factors or the resulting object has to become unfactorizable...

... I think...

Cheers,
Christoph

**Comment by nathanshammah** [comment]
This seems an issue for the [qutip/qutip](https://github.com/qutip/qutip) repository.

**Comment by ajgpitch** [comment]
@chrisgee yes please can you reopen on [qutip/qutip](https://github.com/qutip/qutip). This seems like an interesting question.

> I understand that basis transforms are in development.
Do we know who is doing this?
