### ISSUE TITLE
How to link model notebooks

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip.github.io#50]
@nathanshammah @sahmed95 
We now need to decide how to link the piqs notebooks on the website.

I suggest a section 'Models' under 'Example notebooks' with a subsection 'Permutational Invariant Quantum Solver' with the notebooks linked under that.

Open to alternatives.

**Comment by nathanshammah** [comment]
Sounds great to me.
With regard to the other notebooks that I will upload once we upload the
paper on arXiv, they are of interest for the physics they contain beyond
the method (the piqs model). If they are in the main page of the tutorials
http://qutip.org/tutorials.html they will be more visible and give a more
comprehensive overview of the physics QuTiP can be used for. One could
think of a title just like "Time Evolution". Something like
"Collective-Local Driven-Dissipative Open Quantum Systems" (which might be
too long). Or break them up in different places, as some could go under
"Time Evolution" or QM Lectures. I took care of making them simple and
user-friendly, with introductory equations and references.

They could include the following notebooks, for N two-level systems

- steady-state superradiance

- superradiant light emission

- open Dicke model

- spin squeezing

- time crystals

- Lipkin-Meshkov-Glick model

- long-range Heisenberg model

- Liouvillian spectrum

- resonance fluorescence

- dissipative ultrastrong light-matter coupling

They will all contain new results and comparison to the effects known in
the literature and classic cases (for example the resonance fluorescence of
a single two-level system).




2018-03-20 1:45 GMT+09:00 Alexander Pitchford <notifications@github.com>:

**Comment by nathanshammah** [comment]
This can be closed as we introduced these notebooks under "Permutational Invariant Lindblad Dynamics" in the [Tutorials](http://qutip.org/tutorials.html) section. 

It could be nice to add labels if possible under each section and subsection in order to link to a specific point in that page: Examples, Lectures, Development notebooks, as well as the subsections of the Examples notebooks.
