### ISSUE TITLE
ENH: Steps for testing changes on local webserver

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip.github.io#67]
This explains how to do it
https://stackoverflow.com/questions/24271225/how-do-you-view-a-different-branch-of-your-github-pages

If I can get it to work, then I will add steps to the readme

**Comment by jakelishman** [comment]
This is ancient, but there's also a fairly easy way to do this by (ab)using the "other" method GitHub has to automatically trigger a GitHub pages build.

- fork this repository
- make all the changes you want on a feature branch (let's call it `my-feature`)
- with `my-feature` checked out, create a new branch in your fork called `gh-pages` containing the changes you want, and push it to _your fork_ (`git checkout -b gh-pages && git push <your-fork-remote> gh-pages` (`<your-fork-remote>` is whatever you set it to in git, probably `origin` or `fork`).  Force-push to override it if you've been trying out other stuff before, but be certain you're pushing to your fork.  We're only going to use `gh-pages` as a temporary branch for testing.
- wait ~5 minutes - you might get an email from GitHub when the build is done moaning about `http://qutip.org` already being in use.  You can ignore it - `qutip.org` will only ever point at the main repo.
- visit `<your-github-name>.github.io/qutip.github.io` (e.g. mine would be `jakelishman.github.io/qutip.github.io`)
- once you're happy, it's probably best to delete both your local `gh-pages` branch (`git branch -D gh-pages`, but ensure the changes you want are still accessible in another branch) and the remote branch (`git push --delete <your-fork-remote> gh-pages`).  This is to ensure that your local repo and the remote are clean in case you want to do this again in the future.

**Comment by hodgestar** [comment]
This can be closed once #194 is merged.
