### ISSUE TITLE
benchmark vs time on qutip.org ?

### ISSUE THREAD

**Issue by jrjohansson** [qutip/qutip.github.io#7]
How about including this graph below the current performance graph on qutip.org features page?

https://raw.githubusercontent.com/qutip/qutip-benchmark/master/continuous-benchmark/graphs/summary.png

Or is it a too messy graph?

**Comment by nathanshammah** [comment]
Cool. It could be interesting to have a benchmark information grouped somewhere, either comparing with other packages or just with QuTiP functions as here. 

@Ericgig made some extensive benchmarks in the dev [ssesolver notebooks](https://github.com/qutip/qutip-notebooks/blob/master/development/development-ssesolver-new-methods.ipynb). 

@quantshah and I made some benchmarking of the piqs module at the end of the [overview notebook](http://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/piqs-overview.ipynb), comparing the `uncoupled` basis with the `dicke` basis introduced by piqs.

In the documentation "changelog" there are notes of improvements across multiple orders of magnitude for various tasks. 

I guess it all boils down to whether it is possible to present all this data in an appealing way.

**Comment by hodgestar** [comment]
We should be able to close this once the new https://qutip.org/qutip-benchmarks site is tidied up and linked in to the navigation panel.

**Comment by hodgestar** [comment]
I've linked https://qutip.org/qutip-benchmark so closing this for now. More benchmarks can be added by opening issues or pull requests against the qutip-benchmark repository.
