### ISSUE TITLE
Switch to https

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip.github.io#81]
QuTiP is currently reached at http://qutip.org, not a https protocol. 
Several browsers are giving a disclaimer on http websites and progressively limiting access. It also might affect google search indexing. And of course security issues. 

Github pages says that something is not well configured with the DNS. The host is Namecheap. https://help.github.com/en/articles/troubleshooting-custom-domains#https-errors.

**Comment by akhmerov** [comment]
What's your advanced DNS configuration in namecheap?

This seems to be enough:

![image](https://user-images.githubusercontent.com/2069677/74515123-3d9c2080-4f0e-11ea-82bb-654bc5323498.png)

**Comment by nathanshammah** [comment]
the current maintainers team has no access to this information.

**Comment by paniash** [comment]
Hello! Is the issue being worked on? It would be great if the website had a https protocol.

**Comment by jakelishman** [comment]
Fixed now, subject to DNS caches updating.

**Comment by paniash** [comment]
Most browsers still redirect to http unless specifically mentioned `https://qutip.org`. I think it would be great to remove the http redirect altogether.

**Comment by jakelishman** [comment]
I'll enforce https access from tomorrow - I only just got control of the DNS to make the changes (the issue is that we use an apex domain `qutip.org` rather than `www.qutip.org`, which means we need A records, and ours were pointing to old GH addresses).  Not all DNS caches will have updated yet, so if I enforce it now, there'll be people who can't access the website at all because of broken certificates.  I will swap it over, though.

**Comment by paniash** [comment]
> I'll enforce https access from tomorrow - I only just got control of the DNS to make the changes (the issue is that we use an apex domain `qutip.org` rather than `www.qutip.org`, which means we need A records, and ours were pointing to old GH addresses).  Not all DNS caches will have updated yet, so if I enforce it now, there'll be people who can't access the website at all because of broken certificates.  I will swap it over, though.

Great! Thanks. :-)

**Comment by jakelishman** [comment]
We are now enforced https-only, and all our external hotlinks are updated to reference https assets only as well.  All hyperlinks should also now be https, except in old documentation, and cases where the destination site does not support the protocol.
